Am bug fix
AccessLite/BYT-Golden pull request #15
Opened 2017-02-02 05:16 UTC by anama118118

2017-02-02 17:00 UTC, spacedrabbit requested changes

2017-02-02 17:00 UTC, spacedrabbit commented on BYT/View Controllers/FoaasViewController.swift
> +            if self.foaasView.subtitleLabelConstraint.constant - CGFloat(Double(valueForConstraintConstant) * 1.5) < 16 {
can this not be re-written as `(CGFloat(valueForConstraintConstant) * 1.5) < 16.0`

2017-02-02 17:00 UTC, spacedrabbit commented on BYT/View Controllers/FoaasViewController.swift
> +                print(self.foaasView.subtitleLabelConstraint.constant - CGFloat(Double(valueForConstraintConstant) * 1.5))
same for these two lines

2017-02-02 17:00 UTC, spacedrabbit commented on BYT/View Controllers/FoaasViewController.swift
> +
can you add a short comment on what this dispatch closure is doing? it's not clear to me

2017-02-02 17:01 UTC, spacedrabbit requested changes

2017-02-02 17:01 UTC, spacedrabbit commented on BYT/View Controllers/FoaasViewController.swift
> +        UIView.animate(withDuration: 2.0) {
2 seconds is way too long from a UX perspective. Shorten this to something like  <= 0.3

2017-02-04 02:40 UTC, anama118118 commented on BYT/View Controllers/FoaasViewController.swift
> +
Okay done!

2017-02-04 02:42 UTC, anama118118 commented on BYT/View Controllers/FoaasViewController.swift
> +            if self.foaasView.subtitleLabelConstraint.constant - CGFloat(Double(valueForConstraintConstant) * 1.5) < 16 {
Sorry for the confusing constant name. I just updated it. Please see newest commit.

2017-02-04 02:42 UTC, anama118118 commented on BYT/View Controllers/FoaasViewController.swift
> +        UIView.animate(withDuration: 2.0) {
Done!

2017-02-04 02:58 UTC, spacedrabbit approved these changes

2017-02-04 03:01 UTC, merged